### ISSUE TITLE
Singularites not using tag dictionary correctly

### ISSUE THREAD

**Issue by benbenlaw** [BlakeBr0/ExtendedCrafting#111]
**Describe the bug**
I have 2 different types of copper in my modpack but singualites can only be craft with one type

**To Reproduce**
install mods with multipul types of the same ores

**Expected behavior**
Tag dictionary ores should all work

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).
![image](https://user-images.githubusercontent.com/42780877/98466359-f5710c80-21c6-11eb-8ddc-dc9c1cee3815.png)
Tin ingot saingulairty only uses 1
![image](https://user-images.githubusercontent.com/42780877/98466377-09b50980-21c7-11eb-9387-d00a7f89dbab.png)
2 types of tin in the modpack

Note that both ingots are in the correct tag dictionary

**Versions (please complete the following information):**
 - Minecraft: 1.16.3
 - Forge: 34.1.40
 - Cucumber: 4.1.3
 - Extended Crafting: 3.1.1
 - CraftTweaker (if applicable): none

**Comment by Griefed** [comment]
I can confirm this behaviour as well. I tried modyfing the silver.json to use item's, but instead of making it possible to use both, it instead stopped using the Mystical World one and only accepts the Immersive Engineering one.

Tried with this but failed:
```
{
  "name": "singularity.extendedcrafting.silver",
  "colors": [
    "83aab2",
    "83aab2"
  ],
  "ingredient": {
    "item": "mysticalworld:silver_ingot",
    "item": "immersiveengineering:ingot_silver"
  }
}
```
The original with forge:ingots/silver did not work, even though both ingots use the tag according to CraftTweaker, as seen in the screenshot below.
```
{
  "name": "singularity.extendedcrafting.silver",
  "colors": [
    "83aab2",
    "83aab2"
  ],
  "ingredient": {
    "tag": "forge:ingots/silver"
  }
}
```

![image](https://user-images.githubusercontent.com/44273438/103774634-2fc32280-502d-11eb-9e81-c5d9e870fbd8.png)


Versions:
Minecraft: 1.16.4
Forge: 35.1.28
Cucumber: 4.1.5
Extended Crafting: 3.1.2
CraftTweaker: 7.0.0.63
