### ISSUE TITLE
 Quantum Compressor breaks after crafting one Singularity

### ISSUE THREAD

**Issue by NillerMedDild** [BlakeBr0/ExtendedCrafting#47]
Hey, one of my users just reported an issue with the Singularity crafting - Here goes:
Original report: https://github.com/NillerMedDild/Enigmatica2Expert/issues/220#issuecomment-415818515

#### Issue Description
After a quantum compressor crafts one singularity, they break, They'll continue to show "x/10,000" items in their GUI, and once they hit the 10,000 mark again, they'll show progress as if they're crafting something, but then they just end up eating the items and nothing comes out. The hovering singularity that *should* be visible above them dissappears, too.

![2018-08-24_07 05 29](https://user-images.githubusercontent.com/1569910/44589121-85544880-a76c-11e8-9487-4aae54a5e761.png)

![2018-08-24_07 05 27](https://user-images.githubusercontent.com/1569910/44589127-88e7cf80-a76c-11e8-9ef9-3552406f396d.png)

#### Mod version 
ExtendedCrafting-1.12.2-1.4.2

**Comment by BlakeBr0** [comment]
I've tested this a few times now and I can't seem to reproduce this. I'll look into it a little more later though.

**Comment by codeka** [comment]
I reverted back to 1.12.2-1.4.1 and it's working there. I'll see if I can get a video of it or something...

**Comment by codeka** [comment]
I made a quick video to show my repro: https://youtu.be/JxqrXSPsH4s

Sorry, I don't know much about modded so I'm not sure how to make a smaller repro (without the rest of the modpack, that is). But basically: I'm putting a lot of ingots/s into the compressor, it takes about 50 seconds to craft a singularity (1B EU at 1M EU/t).

As I said, I can keep playing, since reverting back to 1.4.1.

**Comment by BlakeBr0** [comment]
Thanks for the video. I was able to reproduce this so it shouldn't be too difficult to fix.
