### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by MuteTiefling** [BlakeBr0/ExtendedCrafting#81]
More of a question than an issue. Though if it's not possible, then maybe this'll be an improvement request:

I'm looking for a simple way to include all standard 3x3 recipes in the larger tier crafting tables. Currently I have the option on to inherit them into the basic table, but I'd kind of like to make the 5x5 or larger the default crafting table for my pack. This would mean that it would have to handle all of the 3x3 recipes too.

Is there a way I can do this simply through CraftTweaker perhaps? I don't particularly fancy remaking every recipe by hand, but if there's some sort of import method I'm missing there that would simply translate everything to the 5x5 grid, that'd be sweet.

**Comment by BlakeBr0** [comment]
Sorry for the slightly late reply:

The reason I don't do this is because having a small 3x3 recipe in a larger grid means that the table has to scan every possible 3x3 area in the grid for that recipe. With the amount of regular recipes and the size of the larger tables it would become extremely slow.
